name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # - name: Install Docker
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y docker.io
    # - name: Add user to Docker group
    #   run: |
    #     sudo groupadd docker || true
    #     sudo usermod -aG docker $USER
    #     newgrp docker || true
    - name: Run training
      run: python train.py
    # - name: Verify model file
    #   run: test -f diabetes_model.pkl || (echo "Error: diabetes_model.pkl not found" && exit 1)
    - name: Run tests
      run: python -m pytest tests/
    - name: Build Docker image
      run: docker build -t sikanderali/diabetes-prediction-model:latest .
    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push sikanderali/diabetes-prediction-model:latest
